# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Gelting 1"
email: info@hinterhalt.de
locale: "de-DE"
description: >- # this means to ignore newlines until "baseurl:"
  Informationsseite zur Nutzungsänderung der Kulturbühne Hinterhalt in eine Fluggesellschaft
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gelting1.de"

footer:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/HinterhaltKulturb%C3%BChne/featured"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/KulturIsarLoisach"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/kulturbuhnehinterhalt/"
    - label: "PayPal"
      icon: "fab fa-fw fa-paypal"
      url: "https://www.paypal.me/kilev"

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
repository: "gelting1/gelting1.github.io"
github_username:  gelting1

atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
